universe = vanilla

executable              = test.sh
arguments               = $(Process)
log                     = condor_logs/test.log
output                  = condor_logs/outfile.$(Cluster).$(Process).out
error                   = condor_logs/errors.$(Cluster).$(Process).err



# Needed to read .bashrc and conda environment
getenv = True
#request_cpus   = 16
#request_memory = 32768
request_gpus = 1

#+UseNvidiaA100 = True

queue

